# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  sandboxRunnerTag: "v3.2.0"
  webTag: "latest"
  apiTag: "latest"
  

stages:
- stage: SandboxRunner
  displayName: Build and Push SandboxRunner
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build SandboxRunner
      inputs:
        repository: 'jellydock/floodrunner-sandboxrunner'
        command: 'build'
        Dockerfile: '$(System.DefaultWorkingDirectory)/SandboxRunner/Dockerfile'
        tags: '$(sandboxRunnerTag)'

    - task: Docker@2
      displayName: Push SandboxRunner
      inputs:
        containerRegistry: 'JellyDocker DockerHub'
        repository: 'jellydock/floodrunner-sandboxrunner'
        command: 'push'
        tags: '$(sandboxRunnerTag)'

- stage: Web
  dependsOn: []
  displayName: Build and Push Web
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build Web
      inputs:
        repository: 'jellydock/floodrunner-web'
        command: 'build'
        Dockerfile: '$(System.DefaultWorkingDirectory)/web/Dockerfile'
        tags: '$(webTag)'

    - task: Docker@2
      displayName: Push Web
      inputs:
        containerRegistry: 'JellyDocker DockerHub'
        repository: 'jellydock/floodrunner-web'
        command: 'push'
        tags: '$(webTag)'



    
