# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  sandboxRunnerTag: "v3.2.0"

stages:
- stage: BuildSandboxRunner
  displayName: Build and Push SandboxRunner
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/SandboxRunner/Dockerfile'
        tags: |
          $(sandboxRunnerTag)

    - task: Docker@2
      inputs:
        containerRegistry: 'JellyDocker DockerHub'
        repository: 'jellydock/floodrunner-sandboxrunner'
        command: 'push'
        tags: '$(sandboxRunnerTag)'
    
