apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
#  namespace: api
data:
  #mongodb hosting environment (allowed values: 'localhost', 'atlas', 'kubernetes')
  MONGODB_HOSTTYPE: "atlas"
  #mongodb port
  MONGODB_PORT: "27017"
  #name of job database (eg. Agenda database)
  MONGODB_JOB_DATABASE: "flood"
  #name of job database collection (eg. Agenda database collection)
  MONGODB_JOB_COLLECTION: "jobs"
  #name of flood database
  MONGODB_FLOOD_DATABASE: "flood"
  #name of the rabbitmq queue which sandboxrunner results are sent back on
  RABBITMQ_ELEMENTQUEUENAME: "floodelementQueue"
  #name of the azure blob storage resource
  AZURESTORAGE_ACCOUNTNAME: "floodstorage"
  #Auth0 domain
  AUTH_DOMAIN: "javaadpatel.eu.auth0.com"
  #Auth0 audience (used to secure api)
  AUTH_AUDIENCE: "floodrunnerapi"
  #Storage provider selection (allowed values: 'AZURE', 'LOCAL')
  FILE_SERVICE_STRATEGY: "AZURE"
  #maximum number of screenshots that a test can take
  FLOOD_MAXALLOWEDSCREENSHOTS: "10"
  #maximum number of times a test will retry
  FLOOD_MAX_RETRIES: "1"
