mongodb:
  host: "localhost"
  user: "jbird"
  port: 27017
  jobDatabaseName: "flood"
  jobCollectionName: "jobs"
  floodDatabaseName: "flood"

server:
  port: 5001
  fileServiceStrategy: "AZURE"

auth:
  domain: "javaadpatel.eu.auth0.com"
  audience: "floodrunnerapi"

flood:
  maximumAllowedScreenshots: 10
  maxRetries: 1

sandboxRunner:
  url: http://localhost:7071/api/Puppeteer
